name: Geyser-Spigot-Updater
main: com.geyserupdater.spigot.SpigotUpdater
version: 0.2.1
api-version: 1.15
depend: [Geyser-Spigot]
description: Geyser Auto Updating Plugin Addon.

commands:
  geyserupdate:
    description: updating Geyser command
    permission: gupdater.geyserupdate
    aliases: /geyserupdate
